In [8]:
!pip install -q pyomo

In [9]:
from pyomo.environ import *

In [10]:
!apt-get install -y -qq glpk-utils

# Start of Exercise 1:  

min. 2*x1 + 15*x2 − 4*x3 − 6*x4 + 7*x5 − 9*x6 − 1.6*x7

s.t.

Constraint1: x1 + x2 + x3 + x4 + x5 + x6 + x7 = 200     
Constraint2:x1 + x2 ≥ 10,          
Constraint3: 4*x3 + 2*x6 + 3*x7 ≤ 150,     
Constraint4: 10*x1 − x6 + 3*x5 ≥ 20,    
Constraint5: x3 − x5 + 3*x7 ≥ 10,    
Constraint6: x1 ≥ 0,    
Constraint7: x2 ≥ 12,   
Constraint8: x3 ≥ −10,   
Constraint9: x4 ≥ 8,    
Constraint10: x5 ≥ 9,    
Constraint11: x6 ≥ −1,    
Constraint12: x7 ≥ 0 

In [ ]:
# Model creation
model1 = ConcreteModel()

In [ ]:
# Variable declaration
model1.x1 = Var(domain=Reals)
model1.x2 = Var(domain=Reals)
model1.x3 = Var(domain=Reals)
model1.x4 = Var(domain=Reals)
model1.x5 = Var(domain=Reals)
model1.x6 = Var(domain=Reals)
model1.x7 = Var(domain=Reals)

In [ ]:
# Objective declaration
model1.cost = Objective(expr = 2*model1.x1 + 15*model1.x2 - 4*model1.x3 - 6*model1.x4 + 7*model1.x5 -9*model1.x6-1.6*model1.x7, sense=minimize)

In [ ]:
# Constraints declaration
model1.constr1 = Constraint(expr = model1.x1 + model1.x2 + model1.x3 + model1.x4 + model1.x5 + model1.x6 + model1.x7 == 200)
model1.constr2 = Constraint(expr = model1.x1 + model1.x2  >= 10)
model1.constr3 = Constraint(expr = 4*model1.x3 + 2*model1.x6 + 3*model1.x7 <= 150)
model1.constr4 = Constraint(expr = 10*model1.x1 - model1.x6 + 3*model1.x5 >= 20)
model1.constr5 = Constraint(expr = model1.x3 - model1.x5 + 3*model1.x7 >= 10)
model1.constr6 = Constraint(expr = model1.x1 >= 0)
model1.constr7 = Constraint(expr = model1.x2 >= 12)
model1.constr8 = Constraint(expr = model1.x3 >= -10)
model1.constr9 = Constraint(expr = model1.x4 >= 8)
model1.constr10 = Constraint(expr = model1.x5 >= 9)
model1.constr11 = Constraint(expr = model1.x6 >= -1)
model1.constr12 = Constraint(expr = model1.x7 >= 0)

In [ ]:
model1.pprint()

7 Var Declarations
    x1 : Size=1, Index=None
        Key  : Lower : Value : Upper : Fixed : Stale : Domain
        None :  None :  7.35 :  None : False : False :  Reals
    x2 : Size=1, Index=None
        Key  : Lower : Value : Upper : Fixed : Stale : Domain
        None :  None :  12.0 :  None : False : False :  Reals
    x3 : Size=1, Index=None
        Key  : Lower : Value : Upper : Fixed : Stale : Domain
        None :  None : -10.0 :  None : False : False :  Reals
    x4 : Size=1, Index=None
        Key  : Lower : Value            : Upper : Fixed : Stale : Domain
        None :  None : 91.4833333333333 :  None : False : False :  Reals
    x5 : Size=1, Index=None
        Key  : Lower : Value : Upper : Fixed : Stale : Domain
        None :  None :   9.0 :  None : False : False :  Reals
    x6 : Size=1, Index=None
        Key  : Lower : Value : Upper : Fixed : Stale : Domain
        None :  None :  80.5 :  None : False : False :  Reals
    x7 : Size=1, Index=None
        Key  : Lowe

In [ ]:
SolverFactory('glpk', executable='/usr/bin/glpsol').solve(model1).write()

# ==========================================================
# = Solver Results                                         =
# ==========================================================
# ----------------------------------------------------------
#   Problem Information
# ----------------------------------------------------------
Problem: 
- Name: unknown
  Lower bound: -991.166666666667
  Upper bound: -991.166666666667
  Number of objectives: 1
  Number of constraints: 13
  Number of variables: 8
  Number of nonzeros: 26
  Sense: minimize
# ----------------------------------------------------------
#   Solver Information
# ----------------------------------------------------------
Solver: 
- Status: ok
  Termination condition: optimal
  Statistics: 
    Branch and bound: 
      Number of bounded subproblems: 0
      Number of created subproblems: 0
  Error rc: 0
  Time: 0.013065099716186523
# ----------------------------------------------------------
#   Solution Information
# ----------

In [ ]:
# solution display

print("Objective Function Value =",model1.cost())

print("\nvalue of variables at the optimum are following")
print('x1=',model1.x1())
print('x2=',model1.x2())
print('x3=',model1.x3())
print('x4=',model1.x4())
print('x5=',model1.x5())
print('x6=',model1.x6())
print('x7=',model1.x7())

print("\nvalue of first four constraints at optimum")
print(model1.constr1())
print(model1.constr2())
print(model1.constr3())
print(model1.constr4())




Objective Function Value = -991.1666666666665

value of variables at the optimum are following
x1= 7.35
x2= 12.0
x3= -10.0
x4= 91.4833333333333
x5= 9.0
x6= 80.5
x7= 9.66666666666667

value of first four constraints at optimum
199.99999999999997
19.35
150.0
20.0


For the constraint nos. 1,3 & 4, LHS=RHS so these are active constraints.

For constraint no.2, LHS!=RHS so constraint2 is not active.



# ***************END OF EXERCISE 1****************

## **Start of Exercise: 2**

max. 0.043*x1+0.027*x2+0.025*x3+0.022*x4+0.045*x5-0.0275y
s.t.   
Constraint1: x1+x2+x3+x4+x5-y<=100  
Constraint2: x2+x3+x4>=60  
Constraint3: 0.6*x1+0.6*x2-0.4*x3*0.4*x4+3.6*x5<=0  
Constraint4: 4*x1+10*x2-x3+3*x4-3*x5<=0  
Non negativity constraints:x1,x2,x3,x4,x5>=0  
Range for y [0,5]

In [ ]:
#Model Creation
model2 = ConcreteModel()

In [ ]:
#Variables Declaration
model2.x1=Var(domain=NonNegativeReals)
model2.x2=Var(domain=NonNegativeReals)
model2.x3=Var(domain=NonNegativeReals)
model2.x4=Var(domain=NonNegativeReals)
model2.x5=Var(domain=NonNegativeReals)
model2.y=Var(domain=Reals,bounds=(0,5))

In [ ]:
#Objective Declaration
model2.obj=Objective(expr=0.043*model2.x1+0.027*model2.x2+0.025*model2.x3+0.022*model2.x4+0.045*model2.x5-0.027*model2.y,sense=maximize)


In [ ]:
#Constrainsts Declaration
model2.constr1=Constraint(expr=model2.x1+model2.x2+model2.x3+model2.x4+model2.x5-model2.y<=100)
model2.constr2=Constraint(expr=model2.x2+model2.x3+model2.x4>=60)
model2.constr3=Constraint(expr=0.6*model2.x1+0.6*model2.x2-0.4*model2.x3-0.4*model2.x4+3.6*model2.x5<=0)
model2.constr4=Constraint(expr=4*model2.x1+10*model2.x2-model2.x3+3*model2.x4-3*model2.x5<=0)


In [ ]:
model2.pprint()


6 Var Declarations
    x1 : Size=1, Index=None
        Key  : Lower : Value : Upper : Fixed : Stale : Domain
        None :     0 :  None :  None : False :  True : NonNegativeReals
    x2 : Size=1, Index=None
        Key  : Lower : Value : Upper : Fixed : Stale : Domain
        None :     0 :  None :  None : False :  True : NonNegativeReals
    x3 : Size=1, Index=None
        Key  : Lower : Value : Upper : Fixed : Stale : Domain
        None :     0 :  None :  None : False :  True : NonNegativeReals
    x4 : Size=1, Index=None
        Key  : Lower : Value : Upper : Fixed : Stale : Domain
        None :     0 :  None :  None : False :  True : NonNegativeReals
    x5 : Size=1, Index=None
        Key  : Lower : Value : Upper : Fixed : Stale : Domain
        None :     0 :  None :  None : False :  True : NonNegativeReals
    y : Size=1, Index=None
        Key  : Lower : Value : Upper : Fixed : Stale : Domain
        None :     0 :  None :     5 : False :  True :  Reals

1 Objective Declara

In [ ]:
SolverFactory('glpk', executable='/usr/bin/glpsol').solve(model2).write()

# ==========================================================
# = Solver Results                                         =
# ==========================================================
# ----------------------------------------------------------
#   Problem Information
# ----------------------------------------------------------
Problem: 
- Name: unknown
  Lower bound: 2.99781818181818
  Upper bound: 2.99781818181818
  Number of objectives: 1
  Number of constraints: 5
  Number of variables: 7
  Number of nonzeros: 20
  Sense: maximize
# ----------------------------------------------------------
#   Solver Information
# ----------------------------------------------------------
Solver: 
- Status: ok
  Termination condition: optimal
  Statistics: 
    Branch and bound: 
      Number of bounded subproblems: 0
      Number of created subproblems: 0
  Error rc: 0
  Time: 0.0135955810546875
# ----------------------------------------------------------
#   Solution Information
# ---------------

In [ ]:
print("Optimal solution value = ",model2.obj())
print("\nvalue of variables at optimum are")
print("\n x1=",model2.x1())
print("\n x2=",model2.x2())
print("\n x3=",model2.x3())
print("\n x4=",model2.x4())
print("\n x5=",model2.x5())
print("\n y=",model2.y())
print("\nvalue of constraints at optimum are")
print("\n Constraint1=",model2.constr1())
print("\n Constraint2=",model2.constr2())
print("\n Constraint3=",model2.constr3())
print("\n Constraint4=",model2.constr4())


Optimal solution value =  2.9978181818181815

value of variables at optimum are

 x1= 22.9090909090909

 x2= 0.0

 x3= 77.3181818181818

 x4= 0.0

 x5= 4.77272727272727

 y= 5.0

value of constraints at optimum are

 Constraint1= 99.99999999999996

 Constraint2= 77.3181818181818

 Constraint3= -1.0658141036401503e-14

 Constraint4= -1.0658141036401503e-14


Constraint 1,3 and 4 are active as for these value at optimum = RHS value while constraint 2 is not active.  
Also non negativity constraints, x2 and x4 are active as they both are 0 at optimum.  
For y it is obtaining one of the boundary value i.e.5 at optimum so this constraint on y is also active.

## **END OF EXERCISE 2**

## **Start of Exercise 3**

Let no. of kgs of product P produced be 'p' and no. of kgs of product produced be 'q'.

Combined production should be at least 160 kgs: *p+q>=160* ....Constraint1    
Customer requires 45 kgs of P: *p>=45*. ......................Constraint2  
customer also requires 29 kgs of Q;   *q>=29*................Constraint3

Production time requirements for
Product P: 1.25 hrs/kg
Product Q: 0.75 hrs/kg

Total available hrs = 350

1.25*p+0.75*q<=350   ....... Constraint4

Objective is to minimise production cost.
Cost for producing P = Rs. 45/kg
Cost for producing Q = Rs. 80/kg

minimize. 45*P + 80*Q.....Objective function



In [14]:
#Model Creation
model3 = ConcreteModel()

#Variables Declaration
model3.p=Var(domain=NonNegativeReals)
model3.q=Var(domain=NonNegativeReals)

#Objective Declaration
model3.cost=Objective(expr=45*model3.p+80*model3.q,sense=minimize)

#Constraints Declaration
model3.constr1=Constraint(expr=model3.p+model3.q>=160)
model3.constr2=Constraint(expr=model3.p>=45)
model3.constr3=Constraint(expr=model3.q>=29)
model3.constr4=Constraint(expr=1.25*model3.p+0.75*model3.q<=350)

model3.pprint()

SolverFactory('glpk', executable='/usr/bin/glpsol').solve(model3).write()

print("\nMinimum cost = Rs.",model3.cost())
print("\nvalue of products at optimal are")
print("kgs of product P =",model3.p())
print("kgs of product Q =",model3.q())

print("\nvalue of constraints at optimum are")
print("Constraint1=",model3.constr1())
print("Constraint2=",model3.constr2())
print("Constraint3=",model3.constr3())
print("Constraint4=",model3.constr4())


2 Var Declarations
    p : Size=1, Index=None
        Key  : Lower : Value : Upper : Fixed : Stale : Domain
        None :     0 :  None :  None : False :  True : NonNegativeReals
    q : Size=1, Index=None
        Key  : Lower : Value : Upper : Fixed : Stale : Domain
        None :     0 :  None :  None : False :  True : NonNegativeReals

1 Objective Declarations
    cost : Size=1, Index=None, Active=True
        Key  : Active : Sense    : Expression
        None :   True : minimize : 45*p + 80*q

4 Constraint Declarations
    constr1 : Size=1, Index=None, Active=True
        Key  : Lower : Body  : Upper : Active
        None : 160.0 : p + q :  +Inf :   True
    constr2 : Size=1, Index=None, Active=True
        Key  : Lower : Body : Upper : Active
        None :  45.0 :    p :  +Inf :   True
    constr3 : Size=1, Index=None, Active=True
        Key  : Lower : Body : Upper : Active
        None :  29.0 :    q :  +Inf :   True
    constr4 : Size=1, Index=None, Active=True
        Key  :


Constraint1 and Constraint3 are active.  
Constraint2 and Constraint4 are inactive

# Scenario 2 of exercise 3:

Another customer has places order for 95 kgs of P and 75 kgs of Q

Now required minimum quantity for product P = 45+95 = 140 kgs  
Now required minimum quantity for product Q = 29+75 = 104 kgs

New formulation (using same variables p and q as earlier)

p+q>=160.. Constraint1  
p>=140 ...Constraint2   
q>=104 ...Constraint3   
1.25*p+0.75*q<=350...Constraint4

Objective: minimize 45*p+80*q


In [15]:
#Model Creation
model4 = ConcreteModel()

#Variables Declaration
model4.p=Var(domain=NonNegativeReals)
model4.q=Var(domain=NonNegativeReals)

#Objective Declaration
model4.cost=Objective(expr=45*model4.p+80*model4.q,sense=minimize)

#Constraints Declaration
model4.constr1=Constraint(expr=model4.p+model4.q>=160)
model4.constr2=Constraint(expr=model4.p>=140)
model4.constr3=Constraint(expr=model4.q>=104)
model4.constr4=Constraint(expr=1.25*model4.p+0.75*model4.q<=350)

model4.pprint()

SolverFactory('glpk', executable='/usr/bin/glpsol').solve(model4).write()

print("\nMinimum cost = Rs.",model4.cost())
print("\nvalue of products at optimal are")
print("kgs of product P =",model4.p())
print("kgs of product Q =",model4.q())

print("\nvalue of constraints at optimum are")
print("Constraint1=",model4.constr1())
print("Constraint2=",model4.constr2())
print("Constraint3=",model4.constr3())
print("Constraint4=",model4.constr4())


2 Var Declarations
    p : Size=1, Index=None
        Key  : Lower : Value : Upper : Fixed : Stale : Domain
        None :     0 :  None :  None : False :  True : NonNegativeReals
    q : Size=1, Index=None
        Key  : Lower : Value : Upper : Fixed : Stale : Domain
        None :     0 :  None :  None : False :  True : NonNegativeReals

1 Objective Declarations
    cost : Size=1, Index=None, Active=True
        Key  : Active : Sense    : Expression
        None :   True : minimize : 45*p + 80*q

4 Constraint Declarations
    constr1 : Size=1, Index=None, Active=True
        Key  : Lower : Body  : Upper : Active
        None : 160.0 : p + q :  +Inf :   True
    constr2 : Size=1, Index=None, Active=True
        Key  : Lower : Body : Upper : Active
        None : 140.0 :    p :  +Inf :   True
    constr3 : Size=1, Index=None, Active=True
        Key  : Lower : Body : Upper : Active
        None : 104.0 :    q :  +Inf :   True
    constr4 : Size=1, Index=None, Active=True
        Key  :

Constraint2 and Constraint3 are active while Constraint1 and  Constraint4 are inactive.
  
  
As suggested by management the minimum combined production for product P and Q shlould be at least 160 kgs.  
In the first scenario customer demands could be fulfilled just by producing 160 kgs but in scenario 2 customer demand can not be fulfilled by this limit, so Keshar Industries are advised to produce more than 140 kgs of product P and more than 104 kgs of product Q. Combbined it should be more than 244 kgs in order to fulfill current demands and for future orders.